// Created by iWeb 3.0.4 local-build-20140602

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,96),url:'About_Me_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'About_Me_files/stroke_9.png'},{rect:new IWRect(2,-2,96,4),url:'About_Me_files/stroke_10.png'},{rect:new IWRect(98,-2,4,4),url:'About_Me_files/stroke_11.png'},{rect:new IWRect(98,2,4,96),url:'About_Me_files/stroke_12.png'},{rect:new IWRect(98,98,4,4),url:'About_Me_files/stroke_13.png'},{rect:new IWRect(2,98,96,4),url:'About_Me_files/stroke_14.png'},{rect:new IWRect(-2,98,4,4),url:'About_Me_files/stroke_15.png'}],new IWSize(100,100)),stroke_2:new IWStrokeParts([{rect:new IWRect(-2,2,4,96),url:'About_Me_files/stroke_16.png'},{rect:new IWRect(-2,-2,4,4),url:'About_Me_files/stroke_17.png'},{rect:new IWRect(2,-2,96,4),url:'About_Me_files/stroke_18.png'},{rect:new IWRect(98,-2,4,4),url:'About_Me_files/stroke_19.png'},{rect:new IWRect(98,2,4,96),url:'About_Me_files/stroke_20.png'},{rect:new IWRect(98,98,4,4),url:'About_Me_files/stroke_21.png'},{rect:new IWRect(2,98,96,4),url:'About_Me_files/stroke_22.png'},{rect:new IWRect(-2,98,4,4),url:'About_Me_files/stroke_23.png'}],new IWSize(100,100)),stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,326),url:'About_Me_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'About_Me_files/stroke_1.png'},{rect:new IWRect(2,-2,383,4),url:'About_Me_files/stroke_2.png'},{rect:new IWRect(385,-2,4,4),url:'About_Me_files/stroke_3.png'},{rect:new IWRect(385,2,4,326),url:'About_Me_files/stroke_4.png'},{rect:new IWRect(385,328,4,4),url:'About_Me_files/stroke_5.png'},{rect:new IWRect(2,328,383,4),url:'About_Me_files/stroke_6.png'},{rect:new IWRect(-2,328,4,4),url:'About_Me_files/stroke_7.png'}],new IWSize(387,330))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('About_Me_files/About_MeMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id6');applyEffects()}
function onPageUnload()
{Widget.onunload();}
